version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9090
    volumes:
      - .:/code
    ports:
      - "9090:9090"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: